name: CD

on:
  release:
    types:
      - created
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build
      run: scripts/build_pip.sh
    
    - name: Upload
      run: |
         python -m pip install --upgrade twine
         python3 -m twine upload dist/*
      env:
       TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
       TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
